name: Test Earliest Dependencies

on:
  push:
    branches: [ main ]
  pull_request:

permissions: {}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        persist-credentials: false
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
    - name: Install dependencies and force lowest bound
      run: |
        uv sync --upgrade --resolution lowest-direct
    - name: List installed Python packages
      run: uv pip list | tee "$(tty)" | uvx tabulate --header --format github >> $GITHUB_STEP_SUMMARY
    - name: Run tests
      run: uv run pytest
