name: Release
on:
  release:
    types: [published]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.release.tag_name }}
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
        check-latest: true
    - name: Install build dependencies
      run: python -m pip install --upgrade poetry
    - name: Build
      run: poetry build
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
